/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador2;

/**
 *
 * @author Brayan
 */
public class VistaJFrame extends javax.swing.JFrame implements IVista {
    Controlador2 controlador;
    /**
     * Creates new form VistaJFrame
     */
    public VistaJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaTrasiego = new javax.swing.JTextArea();
        jLabelTextoAEnviar = new javax.swing.JLabel();
        jTextFieldTextoAEnviar = new javax.swing.JTextField();
        jButtonEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(102, 102, 102));

        jTextAreaTrasiego.setBackground(new java.awt.Color(153, 255, 255));
        jTextAreaTrasiego.setColumns(20);
        jTextAreaTrasiego.setRows(5);
        jScrollPane1.setViewportView(jTextAreaTrasiego);

        jLabelTextoAEnviar.setText("Mensaje");

        jTextFieldTextoAEnviar.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldTextoAEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTextoAEnviarActionPerformed(evt);
            }
        });

        jButtonEnviar.setBackground(new java.awt.Color(0, 0, 0));
        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 20, Short.MAX_VALUE)
                                .addComponent(jLabelTextoAEnviar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldTextoAEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEnviar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTextoAEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabelTextoAEnviar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEnviar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTextoAEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTextoAEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTextoAEnviarActionPerformed

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JLabel jLabelTextoAEnviar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaTrasiego;
    private javax.swing.JTextField jTextFieldTextoAEnviar;
    // End of variables declaration//GEN-END:variables

    @Override
    public void habilitarEnviar() {
        jButtonEnviar.setEnabled(true);
    }

    @Override
    public void deshabilitarEnviar() {
        jButtonEnviar.setEnabled(false);
    }

    @Override
    public void mostrarMensajeEnTrasiego(String mensaje) {
       jTextAreaTrasiego.append(mensaje + "\n");
    }

    @Override
    public void borrarTextoAEnviar() {
       jTextFieldTextoAEnviar.setText("");
    }
    
    @Override
    public void setControlador(Controlador2 controlador) {
        this.controlador = controlador;
    }

    @Override
    public void hacerVisible() {
        setVisible(true);
    }
    
    @Override
    public void inicializar(){
        jButtonEnviar.setActionCommand(ENVIAR);
        jButtonEnviar.addActionListener(controlador);
    }

    @Override
    public String getMensajeAEnviar() {
        return jTextFieldTextoAEnviar.getText();
    }
}
